"""
Migration: add 20 more outfits (male + female, varied occasions/seasons/styles)
so the recommendation engine has a richer catalogue to work from.
Run once: python migrate_more_outfits.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))

from app import app
from extensions import db
from models.outfit import Outfit

NEW_OUTFITS = [
    # ── FEMALE outfits ────────────────────────────────────────────
    Outfit(
        name='Floral Summer Wrap Dress',
        description='Lightweight floral wrap dress perfect for summer outings',
        top='Wrap dress',
        bottom='N/A',
        shoes='Strappy sandals',
        accessories=['sun hat', 'tote bag'],
        gender='female',
        occasion='casual',
        season='summer',
        style_type='feminine',
        colors=['coral', 'white', 'floral'],
        fabric_types=['rayon', 'chiffon'],
        comfort_score=0.92,
        is_trending=True,
        trend_score=0.88,
        image_url='https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400',
    ),
    Outfit(
        name='Office Power Blazer Set',
        description='Structured blazer and straight-leg trouser set for the boardroom',
        top='Structured blazer',
        bottom='Straight-leg trousers',
        shoes='Block-heel pumps',
        accessories=['leather tote', 'watch'],
        gender='female',
        occasion='work',
        season='all',
        style_type='formal',
        colors=['charcoal', 'white'],
        fabric_types=['wool-blend', 'cotton'],
        comfort_score=0.75,
        is_trending=True,
        trend_score=0.82,
        image_url='https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400',
    ),
    Outfit(
        name='Boho Maxi Skirt Look',
        description='Flowy bohemian maxi skirt with embroidered crop top',
        top='Embroidered crop top',
        bottom='Boho maxi skirt',
        shoes='Leather sandals',
        accessories=['layered necklaces', 'fringe bag'],
        gender='female',
        occasion='casual',
        season='spring',
        style_type='bohemian',
        colors=['earth tones', 'maroon', 'cream'],
        fabric_types=['cotton', 'linen'],
        comfort_score=0.90,
        is_trending=True,
        trend_score=0.85,
        image_url='https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400',
    ),
    Outfit(
        name='Winter Cozy Knit Ensemble',
        description='Oversized cable-knit sweater with fitted jeans and boots',
        top='Cable-knit oversized sweater',
        bottom='Skinny jeans',
        shoes='Ankle boots',
        accessories=['wool scarf', 'beanie'],
        gender='female',
        occasion='casual',
        season='winter',
        style_type='minimalist',
        colors=['cream', 'camel', 'rust'],
        fabric_types=['wool', 'cashmere', 'denim'],
        comfort_score=0.95,
        is_trending=True,
        trend_score=0.87,
        image_url='https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400',
    ),
    Outfit(
        name='Cocktail Party Sequin Dress',
        description='Midi sequin dress with elegant accessories for evening events',
        top='Sequin midi dress',
        bottom='N/A',
        shoes='Gold strappy heels',
        accessories=['clutch bag', 'diamond earrings'],
        gender='female',
        occasion='party',
        season='all',
        style_type='glam',
        colors=['gold', 'champagne', 'black'],
        fabric_types=['sequin fabric', 'lining'],
        comfort_score=0.70,
        is_trending=True,
        trend_score=0.91,
        image_url='https://images.unsplash.com/photo-1566479179817-c5a8ee45bf3c?w=400',
    ),
    Outfit(
        name='Pastel Spring A-Line',
        description='Soft pastel A-line skirt paired with fitted blouse for spring',
        top='Fitted pastel blouse',
        bottom='A-line skirt',
        shoes='Ballet flats',
        accessories=['pearl earrings', 'mini bag'],
        gender='female',
        occasion='date',
        season='spring',
        style_type='a-line',
        colors=['blush', 'lavender', 'white'],
        fabric_types=['cotton', 'polyester'],
        comfort_score=0.88,
        is_trending=False,
        trend_score=0.72,
        image_url='https://images.unsplash.com/photo-1533518975-81f7f3e26768?w=400',
    ),
    Outfit(
        name='Athleisure Yoga Set',
        description='High-waist leggings with matching sports bra and zip-up jacket',
        top='Sports bra + zip-up jacket',
        bottom='High-waist leggings',
        shoes='Running shoes',
        accessories=['gym bag', 'hair tie'],
        gender='female',
        occasion='gym',
        season='all',
        style_type='sporty',
        colors=['cobalt', 'white', 'black'],
        fabric_types=['spandex', 'polyester'],
        comfort_score=0.97,
        is_trending=True,
        trend_score=0.90,
        image_url='https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400',
    ),
    Outfit(
        name='Fall Peplum Office Look',
        description='Peplum blouse and wide-leg trousers for autumn office days',
        top='Peplum blouse',
        bottom='Wide-leg trousers',
        shoes='Loafers',
        accessories=['structured bag', 'belt'],
        gender='female',
        occasion='work',
        season='fall',
        style_type='peplum',
        colors=['mustard', 'forest green', 'beige'],
        fabric_types=['crepe', 'stretch cotton'],
        comfort_score=0.80,
        is_trending=False,
        trend_score=0.69,
        image_url='https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=400',
    ),
    Outfit(
        name='Date Night Wrap Blouse',
        description='Elegant satin wrap blouse with straight midi skirt for romantic evenings',
        top='Satin wrap blouse',
        bottom='Straight midi skirt',
        shoes='Block-heel sandals',
        accessories=['chain bag', 'hoop earrings'],
        gender='female',
        occasion='date',
        season='summer',
        style_type='elegant',
        colors=['emerald', 'ivory'],
        fabric_types=['satin', 'polyester'],
        comfort_score=0.82,
        is_trending=True,
        trend_score=0.86,
        image_url='https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400',
    ),
    Outfit(
        name='Ruffled Winter Formal Gown',
        description='Floor-length ruffled formal gown for galas and weddings',
        top='Ruffled formal gown',
        bottom='N/A',
        shoes='Stiletto heels',
        accessories=['evening bag', 'bracelet'],
        gender='female',
        occasion='formal',
        season='winter',
        style_type='ruffled',
        colors=['deep purple', 'silver'],
        fabric_types=['satin', 'tulle'],
        comfort_score=0.65,
        is_trending=True,
        trend_score=0.84,
        image_url='https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400',
    ),
    # ── MALE outfits ──────────────────────────────────────────────
    Outfit(
        name='Smart Casual Chinos Combo',
        description='Slim-fit chinos with a linen shirt for relaxed smart casual days',
        top='Linen button-up shirt',
        bottom='Slim-fit chinos',
        shoes='Loafers',
        accessories=['leather belt', 'watch'],
        gender='male',
        occasion='casual',
        season='summer',
        style_type='smart-casual',
        colors=['beige', 'white', 'navy'],
        fabric_types=['linen', 'cotton'],
        comfort_score=0.88,
        is_trending=True,
        trend_score=0.85,
        image_url='https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
    ),
    Outfit(
        name='Streetwear Oversized Hoodie',
        description='Dropped-shoulder hoodie with jogger pants and clean sneakers',
        top='Oversized graphic hoodie',
        bottom='Jogger pants',
        shoes='Chunky sneakers',
        accessories=['cap', 'chain'],
        gender='male',
        occasion='casual',
        season='fall',
        style_type='streetwear',
        colors=['black', 'white', 'electric blue'],
        fabric_types=['fleece', 'cotton'],
        comfort_score=0.95,
        is_trending=True,
        trend_score=0.92,
        image_url='https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400',
    ),
    Outfit(
        name='Formal 3-Piece Suit',
        description='Classic 3-piece suit with tie for high-level formal events',
        top='Suit jacket + waistcoat + dress shirt',
        bottom='Suit trousers',
        shoes='Oxford shoes',
        accessories=['silk tie', 'pocket square', 'cufflinks'],
        gender='male',
        occasion='formal',
        season='all',
        style_type='structured',
        colors=['charcoal', 'white', 'navy'],
        fabric_types=['wool', 'cotton'],
        comfort_score=0.72,
        is_trending=False,
        trend_score=0.75,
        image_url='https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    ),
    Outfit(
        name='Athletic Training Outfit',
        description='Fitted performance tee with athletic shorts and training shoes',
        top='Compression performance tee',
        bottom='Athletic shorts',
        shoes='Training shoes',
        accessories=['gym bag', 'sweatband'],
        gender='male',
        occasion='gym',
        season='all',
        style_type='athletic',
        colors=['royal blue', 'black', 'white'],
        fabric_types=['polyester', 'spandex'],
        comfort_score=0.97,
        is_trending=True,
        trend_score=0.89,
        image_url='https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    ),
    Outfit(
        name='Winter Layered Look',
        description='Wool coat over a turtleneck with fitted trousers and leather boots',
        top='Wool overcoat + turtleneck sweater',
        bottom='Fitted trousers',
        shoes='Chelsea boots',
        accessories=['wool scarf', 'leather gloves'],
        gender='male',
        occasion='casual',
        season='winter',
        style_type='layered',
        colors=['camel', 'chocolate brown', 'cream'],
        fabric_types=['wool', 'knit', 'leather'],
        comfort_score=0.87,
        is_trending=True,
        trend_score=0.83,
        image_url='https://images.unsplash.com/photo-1520975954732-35dd22299614?w=400',
    ),
    Outfit(
        name='Party Satin Shirt Look',
        description='Open-collar satin dress shirt with slim trousers for nightlife',
        top='Satin dress shirt',
        bottom='Slim black trousers',
        shoes='Pointed-toe loafers',
        accessories=['chain necklace', 'watch'],
        gender='male',
        occasion='party',
        season='all',
        style_type='fitted',
        colors=['cobalt', 'black', 'gold'],
        fabric_types=['satin', 'stretch fabric'],
        comfort_score=0.78,
        is_trending=True,
        trend_score=0.88,
        image_url='https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400',
    ),
    Outfit(
        name='Spring Minimalist Look',
        description='Clean white tee with relaxed linen trousers and canvas shoes',
        top='White crew-neck tee',
        bottom='Relaxed linen trousers',
        shoes='Canvas sneakers',
        accessories=['minimal watch'],
        gender='male',
        occasion='casual',
        season='spring',
        style_type='minimalist',
        colors=['white', 'beige', 'olive'],
        fabric_types=['cotton', 'linen'],
        comfort_score=0.93,
        is_trending=False,
        trend_score=0.71,
        image_url='https://images.unsplash.com/photo-1463453091185-61582044d556?w=400',
    ),
    Outfit(
        name='Work Slim Blazer Combo',
        description='Navy slim blazer over a crisp shirt with tailored chinos',
        top='Slim-fit navy blazer + dress shirt',
        bottom='Tailored chinos',
        shoes='Derby shoes',
        accessories=['leather briefcase', 'tie'],
        gender='male',
        occasion='work',
        season='all',
        style_type='smart-casual',
        colors=['navy', 'light blue', 'khaki'],
        fabric_types=['wool-blend', 'cotton'],
        comfort_score=0.80,
        is_trending=True,
        trend_score=0.84,
        image_url='https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=400',
    ),
    Outfit(
        name='Date Night Fitted Outfit',
        description='Fitted turtleneck with straight-cut jeans and clean sneakers',
        top='Fitted ribbed turtleneck',
        bottom='Straight-cut dark jeans',
        shoes='Clean white sneakers',
        accessories=['minimal bracelet'],
        gender='male',
        occasion='date',
        season='fall',
        style_type='fitted',
        colors=['black', 'white', 'mustard'],
        fabric_types=['cotton', 'denim'],
        comfort_score=0.86,
        is_trending=True,
        trend_score=0.87,
        image_url='https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    ),
    Outfit(
        name='Festival Boho Kurta',
        description='Embroidered cotton kurta with jogger-style pyjama for festive occasions',
        top='Embroidered cotton kurta',
        bottom='Straight pyjama',
        shoes='Kolhapuri sandals',
        accessories=['watch', 'potli bag'],
        gender='male',
        occasion='party',
        season='all',
        style_type='casual',
        colors=['earth tones', 'maroon', 'gold'],
        fabric_types=['cotton', 'silk'],
        comfort_score=0.90,
        is_trending=True,
        trend_score=0.82,
        image_url='https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400',
    ),
]


def run():
    with app.app_context():
        added = 0
        for outfit in NEW_OUTFITS:
            exists = Outfit.query.filter_by(name=outfit.name).first()
            if not exists:
                db.session.add(outfit)
                added += 1
        db.session.commit()
        total = Outfit.query.count()
        print(f'✅ Added {added} new outfits. Total in DB: {total}')

        # Summary
        from sqlalchemy import func
        genders = db.session.execute(
            db.text('SELECT gender, COUNT(*) FROM outfits GROUP BY gender')
        ).fetchall()
        print('By gender:', {g: c for g, c in genders})
        occasions = db.session.execute(
            db.text('SELECT occasion, COUNT(*) FROM outfits GROUP BY occasion')
        ).fetchall()
        print('By occasion:', {o: c for o, c in occasions})


if __name__ == '__main__':
    run()
