"""
Migration: Structured Fashion Dataset
======================================
Replaces the existing outfit catalogue with 100+ properly structured outfits.
Every outfit has:
  - Exact occasion tag matching frontend values (formal/casual/party/work/gym/date)
  - Explicit gender (male / female — no unisex for category-specific items)
  - body_type_compatibility list
  - Realistic outfit components (top / bottom / shoes / accessories)
  - Skin-tone-aware color palette
  - Season tag

Run once:
    python migrate_structured_outfits.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))

from app import app
from extensions import db
from models.outfit import Outfit


def _img(photo_id, w=600, q=80):
    return f'https://images.unsplash.com/photo-{photo_id}?w={w}&fit=crop&q={q}'


# ---------------------------------------------------------------------------
# Helper maps for occasion → component (used for reference / future validation)
# ---------------------------------------------------------------------------
OCCASION_REQUIRED_COMPONENTS = {
    'formal': {
        'male':   ['blazer or suit jacket', 'formal shirt', 'formal trousers'],
        'female': ['formal dress or blazer', 'formal skirt or trousers'],
    },
    'work': {
        'male':   ['blazer or shirt', 'trousers or chinos'],
        'female': ['blouse or blazer', 'trousers or pencil skirt'],
    },
    'casual': {
        'male':   ['t-shirt or casual shirt', 'jeans or chinos'],
        'female': ['top or casual dress', 'jeans or skirt'],
    },
    'party': {
        'male':   ['dress shirt or statement top', 'trousers or dark jeans'],
        'female': ['party dress or statement outfit'],
    },
    'gym': {
        'male':   ['athletic top', 'shorts or track pants', 'sports shoes'],
        'female': ['sports top', 'leggings or shorts', 'sports shoes'],
    },
    'date': {
        'male':   ['smart shirt or fitted top', 'clean trousers or dark jeans'],
        'female': ['dress or fitted top', 'skirt or jeans'],
    },
}


STRUCTURED_OUTFITS = [

    # =========================================================================
    # FORMAL — MALE (10 outfits)
    # =========================================================================
    Outfit(
        name='Classic Black Tuxedo',
        description='Timeless black tuxedo with white dress shirt and bow tie — the gold standard for black-tie events and galas.',
        top='Black tuxedo jacket + white dress shirt',
        bottom='Black formal trousers',
        shoes='Patent leather Oxford shoes',
        accessories=['Black bow tie', 'Silk pocket square', 'Cufflinks'],
        gender='male',
        occasion='formal',
        season='all',
        style_type='structured',
        colors=['black', 'white', 'silver'],
        fabric_types=['wool', 'silk'],
        comfort_score=0.72,
        body_type_compatibility=['athletic', 'average', 'muscular', 'slim'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1507003211169-0a1dd7228f2d'),
    ),
    Outfit(
        name='Navy Three-Piece Formal Suit',
        description='Structured three-piece navy suit with pocket square and tie — ideal for weddings and corporate galas.',
        top='Navy suit jacket + waistcoat + formal shirt',
        bottom='Navy suit trousers',
        shoes='Dark Oxford shoes',
        accessories=['Silk tie', 'Pocket square', 'Leather watch'],
        gender='male',
        occasion='formal',
        season='all',
        style_type='structured',
        colors=['navy', 'white', 'gold'],
        fabric_types=['wool', 'cotton'],
        comfort_score=0.74,
        body_type_compatibility=['athletic', 'average', 'slim', 'muscular', 'heavy'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1617137968427-85924c800a22'),
    ),
    Outfit(
        name='Charcoal Grey Formal Suit',
        description='Sharp charcoal grey two-piece suit with a crisp white shirt and silver tie for business-formal events.',
        top='Charcoal suit jacket + white dress shirt',
        bottom='Charcoal suit trousers',
        shoes='Grey Oxford shoes',
        accessories=['Silver tie', 'Pocket square', 'Metal cufflinks'],
        gender='male',
        occasion='formal',
        season='all',
        style_type='structured',
        colors=['charcoal', 'white', 'silver'],
        fabric_types=['wool', 'cotton'],
        comfort_score=0.73,
        body_type_compatibility=['average', 'heavy', 'muscular', 'athletic'],
        is_trending=False,
        trend_score=0.75,
        image_url=_img('1521572163474-6864f9cf17ab'),
    ),
    Outfit(
        name='Royal Blue Wedding Suit',
        description='Vibrant royal blue slim suit with a white pocket square — a statement formal look for weddings and celebrations.',
        top='Royal blue slim jacket + white dress shirt',
        bottom='Royal blue suit trousers',
        shoes='White or tan Oxford shoes',
        accessories=['White pocket square', 'Floral lapel pin', 'Watch'],
        gender='male',
        occasion='formal',
        season='spring',
        style_type='fitted',
        colors=['royal blue', 'white', 'gold'],
        fabric_types=['wool-blend', 'cotton'],
        comfort_score=0.76,
        body_type_compatibility=['slim', 'athletic'],
        is_trending=True,
        trend_score=0.85,
        image_url=_img('1519085360753-af0119f7cbe7'),
    ),
    Outfit(
        name='White Linen Formal Suit',
        description='Lightweight white linen formal suit with a light blue shirt — elegant for summer weddings and garden galas.',
        top='White linen suit jacket + light blue dress shirt',
        bottom='White linen suit trousers',
        shoes='Light tan loafers',
        accessories=['Navy pocket square', 'Minimalist watch'],
        gender='male',
        occasion='formal',
        season='summer',
        style_type='minimalist',
        colors=['white', 'cream', 'light blue'],
        fabric_types=['linen', 'cotton'],
        comfort_score=0.82,
        body_type_compatibility=['slim', 'athletic', 'average'],
        is_trending=True,
        trend_score=0.84,
        image_url=_img('1500648767791-00dcc994a43e'),
    ),
    Outfit(
        name='Black Double-Breasted Suit',
        description='Power-dressing black double-breasted suit with white spread collar shirt and gold tie bar.',
        top='Black double-breasted jacket + white dress shirt',
        bottom='Black formal trousers',
        shoes='Black Derby shoes',
        accessories=['Gold tie bar', 'White pocket square', 'Gold cufflinks'],
        gender='male',
        occasion='formal',
        season='winter',
        style_type='structured',
        colors=['black', 'white', 'gold'],
        fabric_types=['wool', 'cotton'],
        comfort_score=0.70,
        body_type_compatibility=['muscular', 'athletic', 'average'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1487222477894-8943e31ef7b2'),
    ),
    Outfit(
        name='Burgundy Formal Suit',
        description='Rich burgundy formal suit with a black shirt and pocket square — bold yet polished for upscale events.',
        top='Burgundy suit jacket + black dress shirt',
        bottom='Burgundy suit trousers',
        shoes='Chelsea boots in dark brown',
        accessories=['Black pocket square', 'Silver watch'],
        gender='male',
        occasion='formal',
        season='fall',
        style_type='fitted',
        colors=['burgundy', 'black', 'silver'],
        fabric_types=['velvet-blend', 'cotton'],
        comfort_score=0.73,
        body_type_compatibility=['slim', 'athletic'],
        is_trending=True,
        trend_score=0.83,
        image_url=_img('1520975954732-35dd22299614'),
    ),
    Outfit(
        name='Classic Morning Suit',
        description='Traditional morning suit in grey with striped trousers, waistcoat, and top hat — for formal day events.',
        top='Grey morning coat + grey waistcoat + white dress shirt',
        bottom='Striped grey formal trousers',
        shoes='Black Oxford shoes',
        accessories=['Silk ascot tie', 'Top hat', 'Gloves'],
        gender='male',
        occasion='formal',
        season='spring',
        style_type='structured',
        colors=['grey', 'black', 'white'],
        fabric_types=['wool', 'cotton', 'silk'],
        comfort_score=0.65,
        body_type_compatibility=['slim', 'athletic', 'average'],
        is_trending=False,
        trend_score=0.68,
        image_url=_img('1506794778202-cad84cf45f1d'),
    ),
    Outfit(
        name='Dark Green Velvet Formal Suit',
        description='Bold dark green velvet suit with a black dress shirt — a sophisticated choice for festive formal events.',
        top='Dark green velvet jacket + black dress shirt',
        bottom='Black formal trousers',
        shoes='Black Chelsea boots',
        accessories=['Black pocket square', 'Gold watch'],
        gender='male',
        occasion='formal',
        season='winter',
        style_type='fitted',
        colors=['forest green', 'black', 'gold'],
        fabric_types=['velvet', 'cotton'],
        comfort_score=0.72,
        body_type_compatibility=['slim', 'athletic'],
        is_trending=True,
        trend_score=0.86,
        image_url=_img('1463453091185-61582044d556'),
    ),
    Outfit(
        name='Camel Herringbone Formal Suit',
        description='Timeless camel herringbone tweed suit with a white shirt and earth-tone tie — relaxed formal elegance.',
        top='Camel herringbone suit jacket + white dress shirt',
        bottom='Matching herringbone trousers',
        shoes='Brown Derby shoes',
        accessories=['Earth-tone tie', 'Brown leather belt', 'Watch'],
        gender='male',
        occasion='formal',
        season='fall',
        style_type='structured',
        colors=['camel', 'white', 'chocolate brown'],
        fabric_types=['tweed', 'cotton'],
        comfort_score=0.77,
        body_type_compatibility=['average', 'heavy', 'muscular', 'athletic'],
        is_trending=False,
        trend_score=0.72,
        image_url=_img('1614252235316-8c857d38b5f4'),
    ),

    # =========================================================================
    # FORMAL — FEMALE (10 outfits)
    # =========================================================================
    Outfit(
        name='Classic Black Evening Gown',
        description='Floor-length black evening gown with a sweetheart neckline — the ultimate choice for black-tie galas.',
        top='Black sweetheart bodice gown (one piece)',
        bottom='N/A',
        shoes='Black stiletto heels',
        accessories=['Diamond earrings', 'Evening clutch', 'Bracelet'],
        gender='female',
        occasion='formal',
        season='all',
        style_type='elegant',
        colors=['black', 'silver'],
        fabric_types=['silk', 'satin'],
        comfort_score=0.68,
        body_type_compatibility=['hourglass', 'pear'],
        is_trending=True,
        trend_score=0.92,
        image_url=_img('1518611012118-696072aa579a'),
    ),
    Outfit(
        name='Navy Blue Formal Pantsuit',
        description='Tailored navy formal pantsuit with a silk blouse — powerful and polished for any high-level formal occasion.',
        top='Navy structured blazer + ivory silk blouse',
        bottom='Wide-leg navy formal trousers',
        shoes='Nude block-heel pumps',
        accessories=['Pearl earrings', 'Gold watch', 'Leather tote'],
        gender='female',
        occasion='formal',
        season='all',
        style_type='structured',
        colors=['navy', 'ivory', 'gold'],
        fabric_types=['wool-blend', 'silk'],
        comfort_score=0.78,
        body_type_compatibility=['rectangle', 'inverted_triangle', 'hourglass'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1573497019940-1c28c88b4f3e'),
    ),
    Outfit(
        name='Emerald Floor-Length Gown',
        description='Dramatic emerald silk floor-length gown with golden accessories — radiant for winter galas.',
        top='Emerald sleeveless halter gown (one piece)',
        bottom='N/A',
        shoes='Gold strappy heels',
        accessories=['Gold necklace', 'Chain clutch', 'Gold bangles'],
        gender='female',
        occasion='formal',
        season='winter',
        style_type='elegant',
        colors=['emerald', 'gold'],
        fabric_types=['silk', 'chiffon'],
        comfort_score=0.70,
        body_type_compatibility=['hourglass', 'rectangle'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1566479179817-c5a8ee45bf3c'),
    ),
    Outfit(
        name='Red Formal Sheath Dress',
        description='Bold red sheath dress with structured shoulders and closed-toe heels — confidence personified.',
        top='Red body-con sheath dress (one piece)',
        bottom='N/A',
        shoes='Black closed-toe heels',
        accessories=['Black clutch', 'Gold earrings'],
        gender='female',
        occasion='formal',
        season='all',
        style_type='fitted',
        colors=['red', 'black', 'gold'],
        fabric_types=['crepe', 'polyester'],
        comfort_score=0.65,
        body_type_compatibility=['hourglass', 'apple'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1509631179647-0177331693ae'),
    ),
    Outfit(
        name='Blush Pink Ball Gown',
        description='Romantic blush pink ball gown with tulle layers and silver accessories — perfect for wedding galas.',
        top='Blush structured corset top (one piece)',
        bottom='N/A',
        shoes='Silver stiletto heels',
        accessories=['Silver tiara', 'Crystal earrings', 'Satin gloves'],
        gender='female',
        occasion='formal',
        season='spring',
        style_type='feminine',
        colors=['blush', 'silver', 'ivory'],
        fabric_types=['tulle', 'satin', 'silk'],
        comfort_score=0.62,
        body_type_compatibility=['hourglass', 'pear'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1533518975-81f7f3e26768'),
    ),
    Outfit(
        name='Ivory Column Formal Dress',
        description='Sleek ivory column dress with a slit and minimalist gold accessories — modern formal sophistication.',
        top='Ivory column dress (one piece)',
        bottom='N/A',
        shoes='Gold pointed-toe heels',
        accessories=['Gold drop earrings', 'Minimalist gold cuff'],
        gender='female',
        occasion='formal',
        season='all',
        style_type='minimalist',
        colors=['ivory', 'gold'],
        fabric_types=['silk', 'satin'],
        comfort_score=0.72,
        body_type_compatibility=['hourglass', 'rectangle'],
        is_trending=True,
        trend_score=0.86,
        image_url=_img('1539109136881-3be0616acf4b'),
    ),
    Outfit(
        name='Midnight Blue Mermaid Gown',
        description='Dramatic midnight blue mermaid gown with beaded embellishments — stunning for black-tie winter events.',
        top='Midnight blue fitted mermaid gown (one piece)',
        bottom='N/A',
        shoes='Black stiletto heels',
        accessories=['Silver clutch', 'Diamond drop earrings', 'Silver bracelet'],
        gender='female',
        occasion='formal',
        season='winter',
        style_type='fitted',
        colors=['midnight blue', 'silver', 'black'],
        fabric_types=['satin', 'beaded lace'],
        comfort_score=0.64,
        body_type_compatibility=['hourglass', 'pear'],
        is_trending=True,
        trend_score=0.91,
        image_url=_img('1544022613-e87ca75a784a'),
    ),
    Outfit(
        name='Wine Red Pleated Formal Dress',
        description='Flowing wine red pleated gown with long sleeves — elegant warmth for autumn and winter formal occasions.',
        top='Wine red long-sleeve pleated gown (one piece)',
        bottom='N/A',
        shoes='Nude heels',
        accessories=['Gold earrings', 'Thin gold belt', 'Evening clutch'],
        gender='female',
        occasion='formal',
        season='fall',
        style_type='wrap',
        colors=['burgundy', 'wine red', 'gold'],
        fabric_types=['chiffon', 'georgette'],
        comfort_score=0.74,
        body_type_compatibility=['apple', 'hourglass', 'rectangle'],
        is_trending=True,
        trend_score=0.84,
        image_url=_img('1515372039744-b8f02a3ae446'),
    ),
    Outfit(
        name='White Formal Trouser Suit',
        description='Modern white power suit with wide-leg trousers and silk camisole — fresh formal elegance for summer events.',
        top='White tailored blazer + white silk camisole',
        bottom='High-waist wide-leg white trousers',
        shoes='Nude pointed-toe heels',
        accessories=['Pearl necklace', 'Gold watch', 'Structured clutch'],
        gender='female',
        occasion='formal',
        season='summer',
        style_type='structured',
        colors=['white', 'ivory', 'gold'],
        fabric_types=['cotton-blend', 'silk'],
        comfort_score=0.78,
        body_type_compatibility=['rectangle', 'inverted_triangle', 'pear'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1591369822096-ffd140ec948f'),
    ),
    Outfit(
        name='Classic Black Blazer Formal Set',
        description='Sharp black blazer with a pencil skirt and silk blouse — versatile power dressing for any formal occasion.',
        top='Black structured blazer + white silk blouse',
        bottom='Black pencil skirt',
        shoes='Black stiletto pumps',
        accessories=['Pearl earrings', 'Black leather clutch'],
        gender='female',
        occasion='formal',
        season='all',
        style_type='fitted',
        colors=['black', 'white', 'silver'],
        fabric_types=['wool-blend', 'silk'],
        comfort_score=0.75,
        body_type_compatibility=['all'],
        is_trending=False,
        trend_score=0.78,
        image_url=_img('1518310383802-640c2de311b2'),  # closest match
    ),

    # =========================================================================
    # CASUAL — MALE (10 outfits)
    # =========================================================================
    Outfit(
        name='Classic White Tee and Straight Jeans',
        description='Clean white crew-neck tee tucked into straight-cut blue jeans — the ultimate casual staple that works everywhere.',
        top='White crew-neck cotton tee',
        bottom='Straight-cut blue jeans',
        shoes='White leather sneakers',
        accessories=['Leather belt', 'Simple watch'],
        gender='male',
        occasion='casual',
        season='all',
        style_type='minimalist',
        colors=['white', 'blue', 'black'],
        fabric_types=['cotton', 'denim'],
        comfort_score=0.95,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1506794778202-cad84cf45f1d'),
    ),
    Outfit(
        name='Polo Shirt and Chino Shorts',
        description='Classic polo shirt with tailored chino shorts and loafers — polished casual for warm-weather outings.',
        top='Slim-fit cotton polo shirt',
        bottom='Chino shorts',
        shoes='Suede loafers',
        accessories=['Woven belt', 'Aviator sunglasses'],
        gender='male',
        occasion='casual',
        season='summer',
        style_type='smart-casual',
        colors=['navy', 'khaki', 'cream'],
        fabric_types=['cotton', 'linen-blend'],
        comfort_score=0.92,
        body_type_compatibility=['athletic', 'average', 'slim'],
        is_trending=True,
        trend_score=0.86,
        image_url=_img('1463453091185-61582044d556'),
    ),
    Outfit(
        name='Denim Jacket Casual Layer',
        description='Denim jacket over a plain tee with slim jeans and sneakers — effortless casual with layered edge.',
        top='Medium wash denim jacket + white tee',
        bottom='Slim black jeans',
        shoes='Low-top canvas sneakers',
        accessories=['Cap', 'Simple bracelet'],
        gender='male',
        occasion='casual',
        season='spring',
        style_type='casual',
        colors=['blue', 'white', 'black'],
        fabric_types=['denim', 'cotton'],
        comfort_score=0.91,
        body_type_compatibility=['slim', 'average'],
        is_trending=True,
        trend_score=0.83,
        image_url=_img('1500648767791-00dcc994a43e'),
    ),
    Outfit(
        name='Henley Shirt and Olive Chinos',
        description='Lightweight henley shirt with olive slim-fit chinos and loafers — refined casual for spring outings.',
        top='White long-sleeve henley shirt',
        bottom='Olive slim-fit chinos',
        shoes='Brown suede loafers',
        accessories=['Leather watch', 'Braided belt'],
        gender='male',
        occasion='casual',
        season='spring',
        style_type='smart-casual',
        colors=['olive', 'white', 'warm brown'],
        fabric_types=['cotton', 'canvas'],
        comfort_score=0.90,
        body_type_compatibility=['average', 'slim', 'athletic'],
        is_trending=False,
        trend_score=0.74,
        image_url=_img('1487222477894-8943e31ef7b2'),
    ),
    Outfit(
        name='Graphic Tee Streetwear Look',
        description='Oversized graphic tee with dark slim jeans and chunky sneakers — bold urban casual style.',
        top='Oversized graphic cotton tee',
        bottom='Dark slim jeans',
        shoes='Chunky platform sneakers',
        accessories=['Chain necklace', 'Cap', 'Crossbody bag'],
        gender='male',
        occasion='casual',
        season='all',
        style_type='streetwear',
        colors=['black', 'white', 'electric blue'],
        fabric_types=['cotton', 'denim'],
        comfort_score=0.94,
        body_type_compatibility=['slim', 'average'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1556821840-3a63f15732ce'),
    ),
    Outfit(
        name='Flannel Shirt and Rugged Jeans',
        description='Button-up flannel shirt over a tee with rugged distressed jeans and boots — cozy casual for cooler days.',
        top='Red tartan flannel shirt + white undershirt',
        bottom='Distressed straight jeans',
        shoes='Brown leather boots',
        accessories=['Leather belt', 'Simple watch'],
        gender='male',
        occasion='casual',
        season='fall',
        style_type='casual',
        colors=['red', 'cream', 'blue', 'chocolate brown'],
        fabric_types=['flannel', 'cotton', 'denim'],
        comfort_score=0.93,
        body_type_compatibility=['average', 'heavy', 'athletic'],
        is_trending=False,
        trend_score=0.70,
        image_url=_img('1520975954732-35dd22299614'),
    ),
    Outfit(
        name='Linen Casual Summer Set',
        description='Relaxed linen shirt and matching linen shorts — breathable and effortlessly cool for summer days.',
        top='Light linen button-down shirt',
        bottom='Tailored linen shorts',
        shoes='Leather sandals',
        accessories=['Minimalist watch', 'Sunglasses'],
        gender='male',
        occasion='casual',
        season='summer',
        style_type='resort',
        colors=['beige', 'white', 'sandy tan'],
        fabric_types=['linen', 'cotton'],
        comfort_score=0.96,
        body_type_compatibility=['slim', 'average', 'athletic'],
        is_trending=True,
        trend_score=0.85,
        image_url=_img('1519085360753-af0119f7cbe7'),
    ),
    Outfit(
        name='Hoodie and Jogger Casual Set',
        description='Relaxed oversized hoodie with matching jogger pants — ultimate comfort for casual days and errands.',
        top='Oversized pullover hoodie',
        bottom='Slim jogger pants',
        shoes='Clean white running shoes',
        accessories=['Sports watch'],
        gender='male',
        occasion='casual',
        season='fall',
        style_type='casual',
        colors=['grey', 'black', 'white'],
        fabric_types=['fleece', 'cotton'],
        comfort_score=0.97,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1534438327276-14e5300c3a48'),
    ),
    Outfit(
        name='Oxford Casual Button-Down',
        description='Light blue Oxford shirt with slim chinos and loafers — smart casual effortlessness for any daytime occasion.',
        top='Light blue Oxford button-down shirt',
        bottom='Slim grey chinos',
        shoes='Brown leather loafers',
        accessories=['Leather watch', 'Minimal bracelet'],
        gender='male',
        occasion='casual',
        season='spring',
        style_type='smart-casual',
        colors=['sky blue', 'grey', 'warm brown'],
        fabric_types=['cotton', 'canvas'],
        comfort_score=0.88,
        body_type_compatibility=['slim', 'average', 'athletic'],
        is_trending=False,
        trend_score=0.72,
        image_url=_img('1521572163474-6864f9cf17ab'),
    ),
    Outfit(
        name='Earth-Tone Winter Casual Layer',
        description='Layered earth-tone knit sweater over a shirt with slim trousers and chelsea boots — relaxed warmth.',
        top='Chunky earth-tone knit sweater + cream shirt',
        bottom='Slim taupe trousers',
        shoes='Brown Chelsea boots',
        accessories=['Wool scarf', 'Leather watch'],
        gender='male',
        occasion='casual',
        season='winter',
        style_type='layered',
        colors=['camel', 'chocolate brown', 'cream', 'rust'],
        fabric_types=['wool', 'knit', 'cotton'],
        comfort_score=0.90,
        body_type_compatibility=['average', 'heavy', 'muscular'],
        is_trending=True,
        trend_score=0.80,
        image_url=_img('1617137968427-85924c800a22'),
    ),

    # =========================================================================
    # CASUAL — FEMALE (10 outfits)
    # =========================================================================
    Outfit(
        name='White Linen Casual Sundress',
        description='Breezy white linen A-line sundress with minimal accessories — effortlessly fresh for summer days out.',
        top='White linen A-line dress (one piece)',
        bottom='N/A',
        shoes='Tan leather sandals',
        accessories=['Woven tote bag', 'Straw hat', 'Simple necklace'],
        gender='female',
        occasion='casual',
        season='summer',
        style_type='a-line',
        colors=['white', 'beige', 'sandy tan'],
        fabric_types=['linen', 'cotton'],
        comfort_score=0.96,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1515372039744-b8f02a3ae446'),
    ),
    Outfit(
        name='High-Waist Jeans and Crop Top',
        description='High-waist straight jeans with a fitted crop tee and sneakers — a youthful, confident casual look.',
        top='Fitted white crop tee',
        bottom='High-waist straight-cut blue jeans',
        shoes='White leather sneakers',
        accessories=['Mini crossbody bag', 'Gold hoops'],
        gender='female',
        occasion='casual',
        season='summer',
        style_type='feminine',
        colors=['blue', 'white', 'gold'],
        fabric_types=['denim', 'cotton'],
        comfort_score=0.90,
        body_type_compatibility=['hourglass', 'pear'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1533518975-81f7f3e26768'),
    ),
    Outfit(
        name='Oversized Sweater and Leggings',
        description='Cozy oversized knit sweater with high-waist leggings — casual comfort with a relaxed autumn vibe.',
        top='Oversized chunky knit sweater',
        bottom='High-waist black leggings',
        shoes='White chunky sneakers',
        accessories=['Mini tote bag', 'Gold earrings'],
        gender='female',
        occasion='casual',
        season='fall',
        style_type='minimalist',
        colors=['cream', 'camel', 'black'],
        fabric_types=['wool', 'cotton', 'spandex'],
        comfort_score=0.97,
        body_type_compatibility=['apple', 'hourglass'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1544022613-e87ca75a784a'),
    ),
    Outfit(
        name='Floral Midi Skirt Casual Set',
        description='Bold floral print midi skirt with a tucked-in fitted top and flats — playful and feminine casual fashion.',
        top='Fitted white ruched top',
        bottom='Floral satin midi skirt',
        shoes='White ballet flats',
        accessories=['Wicker bag', 'Pearl earrings'],
        gender='female',
        occasion='casual',
        season='spring',
        style_type='a-line',
        colors=['coral', 'white', 'floral'],
        fabric_types=['satin', 'cotton'],
        comfort_score=0.88,
        body_type_compatibility=['pear', 'rectangle'],
        is_trending=True,
        trend_score=0.86,
        image_url=_img('1509631179647-0177331693ae'),
    ),
    Outfit(
        name='Mom Jeans and Fitted Tee',
        description='Relaxed mom jeans with a fitted tucked tee and minimal sneakers — the laid-back casual look everyone loves.',
        top='Fitted white crew-neck tee',
        bottom='Light-wash relaxed mom jeans',
        shoes='White low-top sneakers',
        accessories=['Mini shoulder bag', 'Dainty necklace', 'Sunglasses'],
        gender='female',
        occasion='casual',
        season='all',
        style_type='casual',
        colors=['white', 'light blue', 'beige'],
        fabric_types=['denim', 'cotton'],
        comfort_score=0.93,
        body_type_compatibility=['rectangle', 'apple'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1591369822096-ffd140ec948f'),
    ),
    Outfit(
        name='Wide-Leg Linen Jumpsuit',
        description='Relaxed wide-leg linen jumpsuit in beige — effortless minimalist casual for brunch and day outings.',
        top='Wide-leg linen jumpsuit (one piece)',
        bottom='N/A',
        shoes='Leather sandals or cork platforms',
        accessories=['Woven belt', 'Gold earrings', 'Tote bag'],
        gender='female',
        occasion='casual',
        season='summer',
        style_type='wrap',
        colors=['beige', 'cream', 'warm tan'],
        fabric_types=['linen', 'cotton'],
        comfort_score=0.94,
        body_type_compatibility=['hourglass', 'pear'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1539109136881-3be0616acf4b'),
    ),
    Outfit(
        name='Knit Cardigan and Straight Jeans',
        description='Open-front knit cardigan over a simple tee with straight jeans and sneakers — cozy casual with texture.',
        top='Longline open-front knit cardigan + white tee',
        bottom='Straight-leg blue jeans',
        shoes='White low-top sneakers',
        accessories=['Small shoulder bag', 'Simple stud earrings'],
        gender='female',
        occasion='casual',
        season='fall',
        style_type='bohemian',
        colors=['blush', 'cream', 'light blue'],
        fabric_types=['knit', 'cotton', 'denim'],
        comfort_score=0.93,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.85,
        image_url=_img('1566479179817-c5a8ee45bf3c'),
    ),
    Outfit(
        name='Casual Wrap Dress',
        description='Lightweight wrap dress in a neutral print — flattering for all body types and perfect for casual outings.',
        top='Wrap dress (one piece)',
        bottom='N/A',
        shoes='Block-heel sandals or sneakers',
        accessories=['Minimal necklace', 'Sunglasses'],
        gender='female',
        occasion='casual',
        season='spring',
        style_type='wrap',
        colors=['terracotta', 'cream', 'rust'],
        fabric_types=['rayon', 'chiffon'],
        comfort_score=0.92,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.86,
        image_url=_img('1518310383802-640c2de311b2'),
    ),
    Outfit(
        name='Denim Shorts and Striped Top',
        description='Classic denim shorts with a nautical striped tee and white sneakers — vibrant summer casual.',
        top='Navy and white striped cotton tee',
        bottom='Light-wash denim shorts',
        shoes='White canvas sneakers',
        accessories=['White bucket hat', 'Small backpack'],
        gender='female',
        occasion='casual',
        season='summer',
        style_type='casual',
        colors=['white', 'navy', 'light blue'],
        fabric_types=['cotton', 'denim'],
        comfort_score=0.95,
        body_type_compatibility=['slim', 'rectangle'],
        is_trending=True,
        trend_score=0.83,
        image_url=_img('1518611012118-696072aa579a'),
    ),
    Outfit(
        name='Velvet Loungewear Casual Set',
        description='Matching velvet co-ord set in dusty rose — luxurious casual comfort for relaxed winter days.',
        top='Velvet long-sleeve fitted top',
        bottom='Matching velvet straight-leg trousers',
        shoes='White sneakers or slippers',
        accessories=['Gold stud earrings', 'Simple bracelet'],
        gender='female',
        occasion='casual',
        season='winter',
        style_type='minimalist',
        colors=['dusty rose', 'cream', 'blush'],
        fabric_types=['velvet', 'stretch'],
        comfort_score=0.96,
        body_type_compatibility=['hourglass', 'rectangle', 'apple'],
        is_trending=True,
        trend_score=0.84,
        image_url=_img('1573497019940-1c28c88b4f3e'),
    ),

    # =========================================================================
    # PARTY — MALE (8 outfits)
    # =========================================================================
    Outfit(
        name='Black Slim Party Blazer Look',
        description='Slim-fit black blazer over a black tee with slim trousers and pointed loafers — sleek party dressing.',
        top='Slim-fit black blazer + plain black tee',
        bottom='Black slim trousers',
        shoes='Black pointed-toe loafers',
        accessories=['Silver chain','Watch'],
        gender='male',
        occasion='party',
        season='all',
        style_type='fitted',
        colors=['black', 'silver'],
        fabric_types=['wool-blend', 'cotton'],
        comfort_score=0.82,
        body_type_compatibility=['slim', 'athletic', 'average'],
        is_trending=True,
        trend_score=0.91,
        image_url=_img('1507003211169-0a1dd7228f2d'),
    ),
    Outfit(
        name='Gold Sequin Blazer Party Look',
        description='Statement gold sequin blazer with a black tee and dark jeans — guaranteed to stand out at any party.',
        top='Gold sequin blazer + black fitted tee',
        bottom='Black slim jeans',
        shoes='Black Chelsea boots',
        accessories=['Gold watch', 'Minimal chain'],
        gender='male',
        occasion='party',
        season='winter',
        style_type='glam',
        colors=['gold', 'black', 'champagne'],
        fabric_types=['sequin fabric', 'cotton'],
        comfort_score=0.78,
        body_type_compatibility=['slim', 'athletic'],
        is_trending=True,
        trend_score=0.92,
        image_url=_img('1519085360753-af0119f7cbe7'),
    ),
    Outfit(
        name='Navy Velvet Suit Party Look',
        description='Deep navy velvet blazer with a white shirt and black trousers — sophisticated party style for evening events.',
        top='Navy velvet blazer + white dress shirt',
        bottom='Black slim trousers',
        shoes='Black Chelsea boots',
        accessories=['White pocket square', 'Silver watch'],
        gender='male',
        occasion='party',
        season='winter',
        style_type='fitted',
        colors=['navy', 'white', 'black'],
        fabric_types=['velvet', 'cotton'],
        comfort_score=0.80,
        body_type_compatibility=['slim', 'athletic', 'average'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1617137968427-85924c800a22'),
    ),
    Outfit(
        name='Satin Open-Collar Party Shirt',
        description='Cobalt blue satin dress shirt left open-collar with slim trousers — stylish nightlife dressing.',
        top='Cobalt blue satin dress shirt',
        bottom='Black slim trousers',
        shoes='Black pointed loafers',
        accessories=['Chain necklace', 'Watch'],
        gender='male',
        occasion='party',
        season='all',
        style_type='fitted',
        colors=['cobalt', 'black', 'silver'],
        fabric_types=['satin', 'stretch fabric'],
        comfort_score=0.79,
        body_type_compatibility=['slim', 'athletic', 'muscular'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1500648767791-00dcc994a43e'),
    ),
    Outfit(
        name='Bold Tropical Print Party Shirt',
        description='Vibrant tropical-print short-sleeve shirt with white linen trousers — summer party with a resort feel.',
        top='Tropical-print short-sleeve shirt',
        bottom='White linen slim trousers',
        shoes='Tan loafers',
        accessories=['Straw hat', 'Simple bracelet'],
        gender='male',
        occasion='party',
        season='summer',
        style_type='resort',
        colors=['multicolor', 'white', 'green'],
        fabric_types=['cotton', 'linen'],
        comfort_score=0.88,
        body_type_compatibility=['slim', 'average'],
        is_trending=True,
        trend_score=0.85,
        image_url=_img('1463453091185-61582044d556'),
    ),
    Outfit(
        name='Holiday Cranberry Red Blazer',
        description='Festive cranberry red blazer with a white shirt and black trousers — the perfect holiday party statement.',
        top='Cranberry red fitted blazer + white dress shirt',
        bottom='Black slim trousers',
        shoes='Black Oxford shoes',
        accessories=['Black pocket square', 'Silver cufflinks'],
        gender='male',
        occasion='party',
        season='winter',
        style_type='fitted',
        colors=['burgundy', 'white', 'black'],
        fabric_types=['wool-blend', 'cotton'],
        comfort_score=0.77,
        body_type_compatibility=['athletic', 'average', 'slim'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1487222477894-8943e31ef7b2'),
    ),
    Outfit(
        name='Monochrome All-Black Party Look',
        description='Head-to-toe black — fitted roll-neck, slim trousers and Chelsea boots — effortlessly sleek party dressing.',
        top='Black fitted roll-neck sweater',
        bottom='Black slim trousers',
        shoes='Black Chelsea boots',
        accessories=['Silver watch', 'Silver ring'],
        gender='male',
        occasion='party',
        season='fall',
        style_type='minimalist',
        colors=['black', 'silver'],
        fabric_types=['knit', 'stretch fabric'],
        comfort_score=0.84,
        body_type_compatibility=['slim', 'athletic', 'average', 'muscular'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1521572163474-6864f9cf17ab'),
    ),
    Outfit(
        name='Embroidered Festive Kurta',
        description='Rich embroidered kurta with straight pyjama trousers — elegant ethnic party wear for festive celebrations.',
        top='Silk embroidered kurta',
        bottom='Straight pyjama trousers',
        shoes='Embroidered mojari or loafers',
        accessories=['Gold watch', 'Pocket square'],
        gender='male',
        occasion='party',
        season='all',
        style_type='glam',
        colors=['maroon', 'gold', 'earth tones'],
        fabric_types=['silk', 'cotton'],
        comfort_score=0.88,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.82,
        image_url=_img('1614252235316-8c857d38b5f4'),
    ),

    # =========================================================================
    # PARTY — FEMALE (8 outfits)
    # =========================================================================
    Outfit(
        name='Gold Sequin Mini Party Dress',
        description='Dazzling gold sequin mini dress with nude heels — the show-stopping party look that commands every room.',
        top='Gold sequin mini dress (one piece)',
        bottom='N/A',
        shoes='Nude block-heel sandals',
        accessories=['Gold clutch', 'Statement earrings'],
        gender='female',
        occasion='party',
        season='all',
        style_type='glam',
        colors=['gold', 'nude', 'champagne'],
        fabric_types=['sequin', 'lining'],
        comfort_score=0.72,
        body_type_compatibility=['hourglass', 'rectangle'],
        is_trending=True,
        trend_score=0.94,
        image_url=_img('1566479179817-c5a8ee45bf3c'),
    ),
    Outfit(
        name='Hot Pink Body-Con Party Dress',
        description='Vibrant hot pink body-con mini dress with strappy heels — bold, fun, and impossible to miss.',
        top='Hot pink stretch body-con dress (one piece)',
        bottom='N/A',
        shoes='Nude strappy heels',
        accessories=['Gold hoop earrings', 'Minimal clutch'],
        gender='female',
        occasion='party',
        season='summer',
        style_type='fitted',
        colors=['hot pink', 'nude', 'gold'],
        fabric_types=['stretch fabric'],
        comfort_score=0.70,
        body_type_compatibility=['hourglass', 'apple'],
        is_trending=True,
        trend_score=0.91,
        image_url=_img('1518310383802-640c2de311b2'),
    ),
    Outfit(
        name='Champagne Satin Slip Party Dress',
        description='Elegant champagne satin slip dress with thin straps — understated glamour for upscale parties.',
        top='Champagne satin slip dress (one piece)',
        bottom='N/A',
        shoes='Gold strappy stilettos',
        accessories=['Delicate gold necklace', 'Satin clutch'],
        gender='female',
        occasion='party',
        season='all',
        style_type='elegant',
        colors=['champagne', 'nude', 'gold'],
        fabric_types=['satin', 'silk'],
        comfort_score=0.74,
        body_type_compatibility=['hourglass', 'rectangle'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1533518975-81f7f3e26768'),
    ),
    Outfit(
        name='Black Cutout Party Dress',
        description='Sleek black mini dress with strategic cutouts — edgy, modern, and perfectly provocative for parties.',
        top='Black fitted cutout mini dress (one piece)',
        bottom='N/A',
        shoes='Black ankle-strap heels',
        accessories=['Black clutch', 'Silver earrings'],
        gender='female',
        occasion='party',
        season='all',
        style_type='fitted',
        colors=['black', 'silver'],
        fabric_types=['stretch fabric', 'mesh'],
        comfort_score=0.68,
        body_type_compatibility=['hourglass', 'pear'],
        is_trending=True,
        trend_score=0.92,
        image_url=_img('1509631179647-0177331693ae'),
    ),
    Outfit(
        name='Wine Red Velvet Wrap Party Dress',
        description='Luxurious wine red velvet wrap midi dress — sophisticated party elegance for autumn and winter events.',
        top='Wine red velvet wrap dress (one piece)',
        bottom='N/A',
        shoes='Nude pointed-toe heels',
        accessories=['Gold drop earrings', 'Velvet clutch'],
        gender='female',
        occasion='party',
        season='winter',
        style_type='wrap',
        colors=['wine red', 'burgundy', 'nude'],
        fabric_types=['velvet', 'lining'],
        comfort_score=0.76,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1539109136881-3be0616acf4b'),
    ),
    Outfit(
        name='Electric Blue Sequin Midi Dress',
        description='Striking electric blue sequin midi dress with metallic heels for a showstopping party entrance.',
        top='Electric blue sequin midi dress (one piece)',
        bottom='N/A',
        shoes='Silver metallic block heels',
        accessories=['Silver clutch', 'Crystal earrings'],
        gender='female',
        occasion='party',
        season='all',
        style_type='glam',
        colors=['electric blue', 'silver'],
        fabric_types=['sequin', 'lining'],
        comfort_score=0.70,
        body_type_compatibility=['hourglass', 'rectangle', 'pear'],
        is_trending=True,
        trend_score=0.93,
        image_url=_img('1515372039744-b8f02a3ae446'),
    ),
    Outfit(
        name='Feather Trim Party Top Set',
        description='White feather-trim crop top with high-waist wide-leg satin trousers — playful glamour for elevated parties.',
        top='White feather-trim fitted crop top',
        bottom='High-waist ivory satin wide-leg trousers',
        shoes='Clear lucite heels',
        accessories=['Gold necklace', 'Minimal clutch'],
        gender='female',
        occasion='party',
        season='all',
        style_type='glam',
        colors=['white', 'ivory', 'gold'],
        fabric_types=['feather trim', 'satin'],
        comfort_score=0.72,
        body_type_compatibility=['hourglass', 'inverted_triangle'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1544022613-e87ca75a784a'),
    ),
    Outfit(
        name='Sparkle Lehenga Party Set',
        description='Embellished crop blouse and flared lehenga skirt — festive ethnic party wear full of sparkle and tradition.',
        top='Embellished ethnic crop blouse',
        bottom='Flared embroidered lehenga skirt',
        shoes='Gold ethnic heels',
        accessories=['Jhumka earrings', 'Bangles', 'Maang tikka'],
        gender='female',
        occasion='party',
        season='all',
        style_type='glam',
        colors=['maroon', 'gold', 'champagne'],
        fabric_types=['silk', 'embroidery'],
        comfort_score=0.73,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.91,
        image_url=_img('1518611012118-696072aa579a'),
    ),

    # =========================================================================
    # WORK — MALE (8 outfits)
    # =========================================================================
    Outfit(
        name='Business Professional Navy Suit',
        description='Sharp two-piece navy business suit with a white dress shirt and silk tie — boardroom authority.',
        top='Navy slim suit jacket + white dress shirt',
        bottom='Navy suit trousers',
        shoes='Dark Oxford shoes',
        accessories=['Silk tie', 'Leather briefcase', 'Watch'],
        gender='male',
        occasion='work',
        season='all',
        style_type='formal',
        colors=['navy', 'white', 'silver'],
        fabric_types=['wool', 'cotton'],
        comfort_score=0.75,
        body_type_compatibility=['athletic', 'average', 'slim', 'muscular', 'heavy'],
        is_trending=True,
        trend_score=0.85,
        image_url=_img('1487222477894-8943e31ef7b2'),
    ),
    Outfit(
        name='Smart Business Casual Blazer Set',
        description='Medium grey blazer over a crisp checked shirt with tailored chinos — smart-casual that bridges casual Fridays.',
        top='Grey slim blazer + white checked shirt',
        bottom='Tailored khaki chinos',
        shoes='Brown Derby shoes',
        accessories=['Leather belt', 'Watch', 'Leather portfolio'],
        gender='male',
        occasion='work',
        season='all',
        style_type='smart-casual',
        colors=['grey', 'white', 'khaki'],
        fabric_types=['wool-blend', 'cotton'],
        comfort_score=0.82,
        body_type_compatibility=['average', 'slim', 'athletic', 'heavy'],
        is_trending=True,
        trend_score=0.83,
        image_url=_img('1521572163474-6864f9cf17ab'),
    ),
    Outfit(
        name='Work Turtleneck and Tailored Trousers',
        description='Sophisticated black roll-neck with tailored charcoal trousers and loafers — minimal, modern office dressing.',
        top='Black fitted roll-neck sweater',
        bottom='Charcoal straight trousers',
        shoes='Black leather loafers',
        accessories=['Watch', 'Leather bag'],
        gender='male',
        occasion='work',
        season='fall',
        style_type='minimalist',
        colors=['black', 'charcoal', 'silver'],
        fabric_types=['knit', 'stretch fabric'],
        comfort_score=0.85,
        body_type_compatibility=['slim', 'athletic', 'average'],
        is_trending=True,
        trend_score=0.84,
        image_url=_img('1507003211169-0a1dd7228f2d'),
    ),
    Outfit(
        name='Slim Grey Business Suit',
        description='Modern slim-cut grey business suit with a light blue shirt — clean and professional for office meetings.',
        top='Slim grey suit jacket + light blue dress shirt',
        bottom='Slim grey suit trousers',
        shoes='Black Derby shoes',
        accessories=['Navy tie', 'Black leather belt', 'Watch'],
        gender='male',
        occasion='work',
        season='all',
        style_type='formal',
        colors=['grey', 'light blue', 'navy'],
        fabric_types=['wool', 'cotton'],
        comfort_score=0.77,
        body_type_compatibility=['slim', 'athletic'],
        is_trending=False,
        trend_score=0.78,
        image_url=_img('1500648767791-00dcc994a43e'),
    ),
    Outfit(
        name='Work Sport Coat and Chinos',
        description='Tailored navy sport coat over a light button-down with stone chinos and loafers — refined business casual.',
        top='Navy hopsack sport coat + light blue shirt',
        bottom='Stone slim chinos',
        shoes='Brown leather loafers',
        accessories=['Belt', 'Watch', 'Leather portfolio'],
        gender='male',
        occasion='work',
        season='spring',
        style_type='smart-casual',
        colors=['navy', 'light blue', 'stone'],
        fabric_types=['hopsack', 'cotton'],
        comfort_score=0.83,
        body_type_compatibility=['athletic', 'average', 'slim'],
        is_trending=True,
        trend_score=0.81,
        image_url=_img('1517841905240-472988babdf9', 600),
    ),
    Outfit(
        name='Summer Linen Work Blazer Set',
        description='Breathable camel linen blazer with a white tee and slim chinos — cool business casual for summer offices.',
        top='Camel linen blazer + white crew-neck tee',
        bottom='Slim white chinos',
        shoes='White leather sneakers or tan loafers',
        accessories=['Minimal watch', 'Canvas tote'],
        gender='male',
        occasion='work',
        season='summer',
        style_type='smart-casual',
        colors=['camel', 'white', 'beige'],
        fabric_types=['linen', 'cotton'],
        comfort_score=0.88,
        body_type_compatibility=['slim', 'average', 'athletic'],
        is_trending=True,
        trend_score=0.82,
        image_url=_img('1519085360753-af0119f7cbe7'),
    ),
    Outfit(
        name='Office Pinstripe Suit',
        description='Classic charcoal pinstripe suit with a white shirt and black tie — sharp formal office authority.',
        top='Charcoal pinstripe jacket + white shirt',
        bottom='Charcoal pinstripe trousers',
        shoes='Black cap-toe Oxford shoes',
        accessories=['Black tie', 'Black briefcase', 'Cufflinks'],
        gender='male',
        occasion='work',
        season='fall',
        style_type='structured',
        colors=['charcoal', 'white', 'black'],
        fabric_types=['wool', 'cotton'],
        comfort_score=0.72,
        body_type_compatibility=['average', 'athletic', 'slim', 'heavy'],
        is_trending=False,
        trend_score=0.73,
        image_url=_img('1463453091185-61582044d556'),
    ),
    Outfit(
        name='Casual Friday Polo and Chinos',
        description='Classic polo shirt with slim-fit chinos and leather sneakers — the definitive casual Friday office look.',
        top='Navy slim-fit polo shirt',
        bottom='Beige slim chinos',
        shoes='Brown leather sneakers',
        accessories=['Leather belt', 'Watch'],
        gender='male',
        occasion='work',
        season='all',
        style_type='smart-casual',
        colors=['navy', 'beige', 'brown'],
        fabric_types=['cotton', 'canvas'],
        comfort_score=0.88,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.79,
        image_url=_img('1556821840-3a63f15732ce'),
    ),

    # =========================================================================
    # WORK — FEMALE (8 outfits)
    # =========================================================================
    Outfit(
        name='Office Blazer and Pencil Skirt',
        description='Structured black blazer with a slim pencil skirt and nude heels — the cornerstone of professional women\'s dressing.',
        top='Black tailored blazer + white silk blouse',
        bottom='Black pencil skirt',
        shoes='Nude pointed-toe pumps',
        accessories=['Black structured tote', 'Pearl earrings', 'Watch'],
        gender='female',
        occasion='work',
        season='all',
        style_type='structured',
        colors=['black', 'white', 'nude'],
        fabric_types=['wool-blend', 'silk'],
        comfort_score=0.76,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1573497019940-1c28c88b4f3e'),
    ),
    Outfit(
        name='Business Dress with Blazer',
        description='Navy sheath dress paired with a matching blazer and closed-toe pumps — polished and professional.',
        top='Navy structured blazer + navy sheath dress (one piece)',
        bottom='N/A',
        shoes='Black block-heel pumps',
        accessories=['Leather tote', 'Pearl necklace'],
        gender='female',
        occasion='work',
        season='all',
        style_type='fitted',
        colors=['navy', 'white', 'black'],
        fabric_types=['wool-blend', 'crepe'],
        comfort_score=0.77,
        body_type_compatibility=['rectangle', 'hourglass'],
        is_trending=True,
        trend_score=0.86,
        image_url=_img('1591369822096-ffd140ec948f'),
    ),
    Outfit(
        name='Office Wide-Leg Trouser Set',
        description='Wide-leg camel trousers with a fitted cream blouse and loafers — modern, airy office femininity.',
        top='Fitted ivory ribbed turtleneck',
        bottom='Wide-leg camel wool trousers',
        shoes='Black leather loafers',
        accessories=['Minimal gold earrings', 'Structured bag'],
        gender='female',
        occasion='work',
        season='fall',
        style_type='minimalist',
        colors=['camel', 'ivory', 'black'],
        fabric_types=['wool', 'knit'],
        comfort_score=0.84,
        body_type_compatibility=['pear', 'rectangle', 'hourglass'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1539109136881-3be0616acf4b'),
    ),
    Outfit(
        name='Power Burgundy Suit Set',
        description='Tailored burgundy trouser suit with a white blouse — head-to-toe power dressing that commands a room.',
        top='Burgundy structured blazer + white shirt',
        bottom='Matching straight trousers',
        shoes='Nude block pumps',
        accessories=['Gold watch', 'Leather tote'],
        gender='female',
        occasion='work',
        season='all',
        style_type='structured',
        colors=['burgundy', 'white', 'nude'],
        fabric_types=['crepe', 'acetate'],
        comfort_score=0.78,
        body_type_compatibility=['rectangle', 'inverted_triangle', 'hourglass'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1544022613-e87ca75a784a'),
    ),
    Outfit(
        name='Wrap Blouse and Tailored Trousers',
        description='Emerald wrap blouse with high-waist straight black trousers — polished office femininity with color.',
        top='Emerald satin wrap blouse',
        bottom='High-waist black tailored trousers',
        shoes='Black pointed-toe heels',
        accessories=['Gold earrings', 'Black structured bag'],
        gender='female',
        occasion='work',
        season='spring',
        style_type='wrap',
        colors=['emerald', 'black', 'gold'],
        fabric_types=['satin', 'stretch crepe'],
        comfort_score=0.80,
        body_type_compatibility=['hourglass', 'pear', 'apple'],
        is_trending=True,
        trend_score=0.86,
        image_url=_img('1515372039744-b8f02a3ae446'),
    ),
    Outfit(
        name='Business Floral Midi Dress',
        description='Navy printed floral midi dress with a structured belt and block heels — professional yet feminine.',
        top='Printed navy midi dress (one piece)',
        bottom='N/A',
        shoes='Brown block-heel mules',
        accessories=['Thin belt', 'Gold earrings', 'Leather tote'],
        gender='female',
        occasion='work',
        season='spring',
        style_type='a-line',
        colors=['navy', 'white', 'floral'],
        fabric_types=['cotton', 'polyester'],
        comfort_score=0.85,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.84,
        image_url=_img('1533518975-81f7f3e26768'),
    ),
    Outfit(
        name='Smart Work Blazer and Straight Jeans',
        description='White linen blazer with a simple tee and straight dark jeans — the chic casual-Friday office combination.',
        top='White tailored linen blazer + white tee',
        bottom='Dark straight-leg jeans',
        shoes='White pointed-toe loafers',
        accessories=['Minimal gold earrings', 'Tote bag'],
        gender='female',
        occasion='work',
        season='summer',
        style_type='minimalist',
        colors=['white', 'dark blue', 'navy'],
        fabric_types=['linen', 'cotton', 'denim'],
        comfort_score=0.88,
        body_type_compatibility=['rectangle', 'hourglass'],
        is_trending=True,
        trend_score=0.85,
        image_url=_img('1518310383802-640c2de311b2'),
    ),
    Outfit(
        name='Smart Work Jumpsuit',
        description='Sleek all-black tailored jumpsuit with a slim belt — effortless professional style in one piece.',
        top='Black tailored jumpsuit (one piece)',
        bottom='N/A',
        shoes='Black block-heel sandals',
        accessories=['Thin gold belt', 'Gold earrings', 'Structured tote'],
        gender='female',
        occasion='work',
        season='all',
        style_type='minimalist',
        colors=['black', 'gold'],
        fabric_types=['crepe', 'polyester'],
        comfort_score=0.83,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1566479179817-c5a8ee45bf3c'),
    ),

    # =========================================================================
    # GYM — MALE (7 outfits)
    # =========================================================================
    Outfit(
        name='Performance Running Outfit',
        description='Moisture-wicking running tee with lightweight running shorts and performance trainers — built to run fast.',
        top='Black moisture-wicking running tee',
        bottom='Black running shorts with mesh lining',
        shoes='Lightweight running trainers',
        accessories=['Running watch', 'Earphones', 'Water bottle'],
        gender='male',
        occasion='gym',
        season='all',
        style_type='athletic',
        colors=['black', 'neon green', 'white'],
        fabric_types=['polyester', 'mesh'],
        comfort_score=0.97,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1534438327276-14e5300c3a48'),
    ),
    Outfit(
        name='Athletic Tank and Training Shorts',
        description='Sleeveless athletic tank with training shorts and cross-training shoes — summer gym essentials.',
        top='White deep-cut athletic tank',
        bottom='Navy training shorts',
        shoes='Cross-training shoes',
        accessories=['Sweatband', 'Gym bag'],
        gender='male',
        occasion='gym',
        season='summer',
        style_type='sporty',
        colors=['white', 'navy', 'black'],
        fabric_types=['polyester', 'spandex'],
        comfort_score=0.97,
        body_type_compatibility=['athletic', 'muscular', 'slim'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1463453091185-61582044d556'),
    ),
    Outfit(
        name='Compression Gym Set',
        description='Full compression tee and compression tights — maximum performance for weightlifting and HIIT sessions.',
        top='Black compression performance tee',
        bottom='Black compression tights',
        shoes='Weightlifting trainers',
        accessories=['Weight belt', 'Gym gloves'],
        gender='male',
        occasion='gym',
        season='all',
        style_type='athletic',
        colors=['black', 'grey', 'silver'],
        fabric_types=['spandex', 'polyester'],
        comfort_score=0.95,
        body_type_compatibility=['muscular', 'athletic', 'slim'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1519085360753-af0119f7cbe7'),
    ),
    Outfit(
        name='Jogger and Hoodie Gym Set',
        description='Slim athletic joggers with a lightweight hoodie — versatile gym-to-street athleisure look.',
        top='Charcoal lightweight gym hoodie',
        bottom='Slim charcoal athletic joggers',
        shoes='Running shoes',
        accessories=['Sports watch', 'Earphones'],
        gender='male',
        occasion='gym',
        season='fall',
        style_type='sporty',
        colors=['charcoal', 'white', 'black'],
        fabric_types=['fleece', 'polyester'],
        comfort_score=0.96,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1556821840-3a63f15732ce'),
    ),
    Outfit(
        name='Athletic Track Suit',
        description='Classic navy and white track suit jacket and matching pants — warm-up and cool-down ready.',
        top='Navy track jacket',
        bottom='Navy track pants',
        shoes='Retro running shoes',
        accessories=['Sports bag', 'Water bottle'],
        gender='male',
        occasion='gym',
        season='winter',
        style_type='athletic',
        colors=['navy', 'white', 'royal blue'],
        fabric_types=['polyester', 'nylon'],
        comfort_score=0.94,
        body_type_compatibility=['all'],
        is_trending=False,
        trend_score=0.77,
        image_url=_img('1520975954732-35dd22299614'),
    ),
    Outfit(
        name='Performance Long-Sleeve Gym Set',
        description='Thermal long-sleeve performance top with athletic leggings for cold-weather training.',
        top='Royal blue thermal long-sleeve top',
        bottom='Black athletic leggings',
        shoes='Trail running shoes',
        accessories=['Running gloves', 'Headband'],
        gender='male',
        occasion='gym',
        season='winter',
        style_type='athletic',
        colors=['royal blue', 'black'],
        fabric_types=['thermal fabric', 'spandex'],
        comfort_score=0.93,
        body_type_compatibility=['slim', 'athletic', 'average'],
        is_trending=True,
        trend_score=0.83,
        image_url=_img('1500648767791-00dcc994a43e'),
    ),
    Outfit(
        name='Cycling Bib and Jersey Set',
        description='Professional cycling jersey and bib shorts — streamlined performance gear for cycling sessions.',
        top='Black and yellow cycling jersey',
        bottom='Black cycling bib shorts',
        shoes='Cycling cleats',
        accessories=['Cycling helmet', 'Gloves', 'Sunglasses'],
        gender='male',
        occasion='gym',
        season='summer',
        style_type='athletic',
        colors=['black', 'yellow', 'white'],
        fabric_types=['spandex', 'polyester'],
        comfort_score=0.96,
        body_type_compatibility=['slim', 'athletic'],
        is_trending=False,
        trend_score=0.74,
        image_url=_img('1617137968427-85924c800a22'),
    ),

    # =========================================================================
    # GYM — FEMALE (7 outfits)
    # =========================================================================
    Outfit(
        name='High-Waist Yoga Legging Set',
        description='Matching high-waist yoga leggings and sports bra with a zip-up jacket — yoga-to-street ready.',
        top='Mint green sports bra + zip-up jacket',
        bottom='Matching high-waist yoga leggings',
        shoes='Lightweight yoga trainers',
        accessories=['Hair tie', 'Yoga mat bag', 'Sports watch'],
        gender='female',
        occasion='gym',
        season='all',
        style_type='sporty',
        colors=['mint', 'white', 'sage green'],
        fabric_types=['spandex', 'nylon'],
        comfort_score=0.98,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.92,
        image_url=_img('1518310383802-640c2de311b2'),
    ),
    Outfit(
        name='Running Performance Set',
        description='Sleek running crop top and high-waist shorts — ideal for outdoor runs and cardio sessions.',
        top='Coral fitted running crop top',
        bottom='Black high-waist running shorts',
        shoes='Lightweight running shoes',
        accessories=['Running arm band', 'Earphones'],
        gender='female',
        occasion='gym',
        season='summer',
        style_type='athletic',
        colors=['coral', 'black', 'white'],
        fabric_types=['polyester', 'spandex'],
        comfort_score=0.97,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1534438327276-14e5300c3a48'),
    ),
    Outfit(
        name='Sports Bra and Shorts Gym Set',
        description='High-neck sports bra with matching bike shorts — minimalist gym look for studio classes.',
        top='Black high-neck sports bra',
        bottom='Black bike shorts',
        shoes='White training shoes',
        accessories=['Gym bag', 'Water bottle'],
        gender='female',
        occasion='gym',
        season='summer',
        style_type='sporty',
        colors=['black', 'hot pink', 'white'],
        fabric_types=['spandex', 'microfibre'],
        comfort_score=0.97,
        body_type_compatibility=['slim', 'athletic', 'hourglass'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1519085360753-af0119f7cbe7'),
    ),
    Outfit(
        name='Cobalt Athletic Matching Set',
        description='Cobalt blue sports bra and high-waist leggings set with white trainers — coordinated gym perfection.',
        top='Cobalt blue ribbed sports bra',
        bottom='Cobalt blue high-waist leggings',
        shoes='White clean sneakers',
        accessories=['Sports watch', 'Hair tie'],
        gender='female',
        occasion='gym',
        season='all',
        style_type='athletic',
        colors=['cobalt', 'white', 'navy'],
        fabric_types=['nylon', 'spandex'],
        comfort_score=0.96,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.91,
        image_url=_img('1556821840-3a63f15732ce'),
    ),
    Outfit(
        name='Compression Training Set',
        description='Grey full-length compression leggings with a fitted athletic top — serious performance training gear.',
        top='Fitted grey athletic long-sleeve top',
        bottom='Grey full-length compression leggings',
        shoes='Cross-training shoes',
        accessories=['Gym gloves', 'Sports bag'],
        gender='female',
        occasion='gym',
        season='all',
        style_type='athletic',
        colors=['grey', 'neon yellow', 'black'],
        fabric_types=['spandex', 'polyester'],
        comfort_score=0.95,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1509631179647-0177331693ae'),
    ),
    Outfit(
        name='Zip-Up Workout Combo',
        description='Royal blue zip-up jacket with crop leggings for autumn training sessions — warm-up and workout in one.',
        top='Royal blue fitted zip-up track jacket',
        bottom='Matching black and blue capri leggings',
        shoes='Running shoes',
        accessories=['Earphones', 'Water bottle'],
        gender='female',
        occasion='gym',
        season='fall',
        style_type='sporty',
        colors=['royal blue', 'black', 'white'],
        fabric_types=['polyester', 'nylon'],
        comfort_score=0.94,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.85,
        image_url=_img('1544022613-e87ca75a784a'),
    ),
    Outfit(
        name='Performance Athletic Dress',
        description='Built-in short athletic dress with moisture-wicking fabric — versatile for tennis, yoga, or general gym.',
        top='Black athletic performance dress (one piece)',
        bottom='N/A',
        shoes='White trainers',
        accessories=['Hair band', 'Sports watch'],
        gender='female',
        occasion='gym',
        season='summer',
        style_type='athletic',
        colors=['black', 'white'],
        fabric_types=['polyester', 'spandex'],
        comfort_score=0.96,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.83,
        image_url=_img('1566479179817-c5a8ee45bf3c'),
    ),

    # =========================================================================
    # DATE — MALE (7 outfits)
    # =========================================================================
    Outfit(
        name='Smart Casual Date Outfit',
        description='White linen shirt with dark slim jeans and clean leather loafers — relaxed, attractive date dressing.',
        top='White slim-fit linen shirt',
        bottom='Dark navy slim jeans',
        shoes='Brown leather loafers',
        accessories=['Minimal watch', 'Leather belt'],
        gender='male',
        occasion='date',
        season='spring',
        style_type='smart-casual',
        colors=['white', 'navy', 'warm brown'],
        fabric_types=['linen', 'denim'],
        comfort_score=0.91,
        body_type_compatibility=['slim', 'average', 'athletic'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1487222477894-8943e31ef7b2'),
    ),
    Outfit(
        name='Date Night Blazer Look',
        description='Navy sport blazer over a white tee with dark jeans and Chelsea boots — elevated casual for a dinner date.',
        top='Navy slim sport blazer + white tee',
        bottom='Dark slim jeans',
        shoes='Brown Chelsea boots',
        accessories=['Watch', 'Leather belt'],
        gender='male',
        occasion='date',
        season='all',
        style_type='smart-casual',
        colors=['navy', 'white', 'chocolate brown'],
        fabric_types=['cotton', 'denim', 'leather'],
        comfort_score=0.88,
        body_type_compatibility=['slim', 'athletic', 'average'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1500648767791-00dcc994a43e'),
    ),
    Outfit(
        name='Olive Casual Chic Date Outfit',
        description='Slim olive twill shirt with dark chinos and leather sneakers — understated masculinity for a casual date.',
        top='Slim olive twill shirt',
        bottom='Dark slim chinos',
        shoes='White leather sneakers',
        accessories=['Watch', 'Minimal ring'],
        gender='male',
        occasion='date',
        season='spring',
        style_type='casual',
        colors=['olive', 'chocolate brown', 'white'],
        fabric_types=['cotton', 'canvas'],
        comfort_score=0.91,
        body_type_compatibility=['average', 'slim', 'athletic'],
        is_trending=True,
        trend_score=0.86,
        image_url=_img('1463453091185-61582044d556'),
    ),
    Outfit(
        name='Romantic Black Turtleneck Date Look',
        description='Fitted black ribbed turtleneck with dark tailored trousers and Chelsea boots — brooding sophistication.',
        top='Fitted black ribbed turtleneck',
        bottom='Black slim tailored trousers',
        shoes='Black leather Chelsea boots',
        accessories=['Silver watch', 'Minimal bracelet'],
        gender='male',
        occasion='date',
        season='fall',
        style_type='minimalist',
        colors=['black', 'charcoal', 'silver'],
        fabric_types=['knit', 'stretch fabric'],
        comfort_score=0.87,
        body_type_compatibility=['slim', 'athletic', 'muscular'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1507003211169-0a1dd7228f2d'),
    ),
    Outfit(
        name='Casual Summer Date Look',
        description='Printed light cotton shirt with chino shorts and loafers — relaxed summer date charm.',
        top='Light cotton print shirt',
        bottom='Sand-color chino shorts',
        shoes='White canvas loafers',
        accessories=['Sunglasses', 'Minimal watch'],
        gender='male',
        occasion='date',
        season='summer',
        style_type='resort',
        colors=['beige', 'white', 'sandy tan'],
        fabric_types=['cotton', 'linen'],
        comfort_score=0.93,
        body_type_compatibility=['slim', 'average'],
        is_trending=True,
        trend_score=0.84,
        image_url=_img('1520975954732-35dd22299614'),
    ),
    Outfit(
        name='Winter Date Night Coat Look',
        description='Camel overcoat over a navy roll-neck with slim dark jeans — polished warmth for a romantic winter evening.',
        top='Camel wool overcoat + navy fitted roll-neck',
        bottom='Slim dark indigo jeans',
        shoes='Dark Brown Chelsea boots',
        accessories=['Leather gloves', 'Watch', 'Scarf'],
        gender='male',
        occasion='date',
        season='winter',
        style_type='layered',
        colors=['camel', 'navy', 'dark indigo'],
        fabric_types=['wool', 'knit', 'denim'],
        comfort_score=0.86,
        body_type_compatibility=['slim', 'average', 'athletic'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1521572163474-6864f9cf17ab'),
    ),
    Outfit(
        name='Fitted Burgundy Date Shirt',
        description='Fitted burgundy stretch shirt with dark slim jeans and pointed loafers — warm-toned date-night edge.',
        top='Fitted burgundy stretch shirt',
        bottom='Dark slim jeans',
        shoes='Black pointed loafers',
        accessories=['Silver watch', 'Leather belt'],
        gender='male',
        occasion='date',
        season='fall',
        style_type='fitted',
        colors=['burgundy', 'black', 'silver'],
        fabric_types=['polyester blend', 'denim'],
        comfort_score=0.84,
        body_type_compatibility=['slim', 'athletic', 'average'],
        is_trending=True,
        trend_score=0.87,
        image_url=_img('1617137968427-85924c800a22'),
    ),

    # =========================================================================
    # DATE — FEMALE (7 outfits)
    # =========================================================================
    Outfit(
        name='Romantic Floral Date Dress',
        description='Fitted floral wrap dress with block heels — feminine and flattering for a romantic daytime date.',
        top='Floral wrap midi dress (one piece)',
        bottom='N/A',
        shoes='Nude block-heel sandals',
        accessories=['Minimal necklace', 'Small clutch'],
        gender='female',
        occasion='date',
        season='spring',
        style_type='wrap',
        colors=['coral', 'blush', 'floral'],
        fabric_types=['chiffon', 'rayon'],
        comfort_score=0.90,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.91,
        image_url=_img('1515372039744-b8f02a3ae446'),
    ),
    Outfit(
        name='Date Night Black Mini Dress',
        description='Classic form-fitting black mini dress with strappy heels — effortlessly alluring for an evening date.',
        top='Black fitted mini dress (one piece)',
        bottom='N/A',
        shoes='Nude strappy heels',
        accessories=['Gold necklace', 'Mini clutch'],
        gender='female',
        occasion='date',
        season='all',
        style_type='fitted',
        colors=['black', 'gold', 'nude'],
        fabric_types=['stretch fabric', 'lining'],
        comfort_score=0.74,
        body_type_compatibility=['hourglass', 'pear'],
        is_trending=True,
        trend_score=0.92,
        image_url=_img('1518611012118-696072aa579a'),
    ),
    Outfit(
        name='Boho Date Garden Look',
        description='Flowy boho maxi dress with leather sandals — relaxed, natural beauty for an outdoor date.',
        top='Ivory floral boho maxi dress (one piece)',
        bottom='N/A',
        shoes='Brown leather flat sandals',
        accessories=['Layered necklaces', 'Wicker bag', 'Flower hair pin'],
        gender='female',
        occasion='date',
        season='summer',
        style_type='bohemian',
        colors=['ivory', 'floral', 'earth tones'],
        fabric_types=['cotton', 'rayon'],
        comfort_score=0.93,
        body_type_compatibility=['all'],
        is_trending=True,
        trend_score=0.88,
        image_url=_img('1509631179647-0177331693ae'),
    ),
    Outfit(
        name='Smart Fitted Date Blouse Set',
        description='Fitted silk blouse tucked into straight-leg clean jeans with pointed-toe heels — polished casual date energy.',
        top='Blush satin fitted blouse',
        bottom='Dark straight-leg jeans',
        shoes='Nude pointed-toe mules',
        accessories=['Gold drop earrings', 'Mini bag'],
        gender='female',
        occasion='date',
        season='all',
        style_type='feminine',
        colors=['blush', 'dark navy', 'nude'],
        fabric_types=['satin', 'denim'],
        comfort_score=0.86,
        body_type_compatibility=['hourglass', 'pear', 'rectangle'],
        is_trending=True,
        trend_score=0.90,
        image_url=_img('1573497019940-1c28c88b4f3e'),
    ),
    Outfit(
        name='Winter Date Red Dress',
        description='Fitted long-sleeve red midi dress — bold, warm and deeply romantic for winter date nights.',
        top='Red fitted long-sleeve midi dress (one piece)',
        bottom='N/A',
        shoes='Black ankle-strap heels',
        accessories=['Gold earrings', 'Mini clutch'],
        gender='female',
        occasion='date',
        season='winter',
        style_type='fitted',
        colors=['red', 'black', 'gold'],
        fabric_types=['knit', 'stretch'],
        comfort_score=0.78,
        body_type_compatibility=['hourglass', 'apple'],
        is_trending=True,
        trend_score=0.91,
        image_url=_img('1533518975-81f7f3e26768'),
    ),
    Outfit(
        name='Casual Date Jeans and Blazer',
        description='White fitted blazer over a simple cami with light wash jeans and sneakers — cute and cool casual date.',
        top='White tailored blazer + white cami',
        bottom='Light-wash straight jeans',
        shoes='White platform sneakers',
        accessories=['Gold rings', 'Small shoulder bag'],
        gender='female',
        occasion='date',
        season='spring',
        style_type='minimalist',
        colors=['white', 'light blue', 'gold'],
        fabric_types=['cotton', 'denim'],
        comfort_score=0.91,
        body_type_compatibility=['rectangle', 'hourglass'],
        is_trending=True,
        trend_score=0.89,
        image_url=_img('1591369822096-ffd140ec948f'),
    ),
    Outfit(
        name='Emerald Satin Slip Date Dress',
        description='Elegant emerald satin slip dress with a delicate gold necklace — sophisticated minimalism for dinner dates.',
        top='Emerald satin slip midi dress (one piece)',
        bottom='N/A',
        shoes='Gold strappy heels',
        accessories=['Delicate gold necklace', 'Evening clutch'],
        gender='female',
        occasion='date',
        season='summer',
        style_type='elegant',
        colors=['emerald', 'gold'],
        fabric_types=['satin', 'silk-blend'],
        comfort_score=0.80,
        body_type_compatibility=['hourglass', 'rectangle'],
        is_trending=True,
        trend_score=0.93,
        image_url=_img('1544022613-e87ca75a784a'),
    ),
]


def run():
    with app.app_context():
        # Step 1 – Add body_type_compatibility column if it doesn't exist yet
        try:
            db.session.execute(
                db.text('ALTER TABLE outfits ADD COLUMN body_type_compatibility JSON')
            )
            db.session.commit()
            print('✅ Added body_type_compatibility column.')
        except Exception:
            db.session.rollback()
            print('ℹ️  body_type_compatibility column already exists.')

        # Step 2 – Delete all existing outfits (Recommendations/Feedbacks too via FK)
        try:
            db.session.execute(db.text('DELETE FROM recommendations'))
            db.session.execute(db.text('DELETE FROM user_feedbacks'))
            db.session.execute(db.text('DELETE FROM outfit_interactions'))
            db.session.execute(db.text('DELETE FROM outfits'))
            db.session.commit()
            print('🗑️  Cleared old outfit data.')
        except Exception as e:
            db.session.rollback()
            print(f'⚠️  Could not clear old outfits: {e}')

        # Step 3 – Insert structured outfits
        for outfit in STRUCTURED_OUTFITS:
            db.session.add(outfit)
        db.session.commit()

        total = len(STRUCTURED_OUTFITS)
        print(f'✅ Inserted {total} structured outfits.')

        # Step 4 – Print summary
        from sqlalchemy import text
        gender_rows = db.session.execute(
            text("SELECT gender, COUNT(*) cnt FROM outfits GROUP BY gender")
        ).fetchall()
        occ_rows = db.session.execute(
            text("SELECT occasion, COUNT(*) cnt FROM outfits GROUP BY occasion ORDER BY occasion")
        ).fetchall()

        print('\nBreakdown by gender:')
        for g, c in gender_rows:
            print(f'  {g or "unset":10} → {c}')
        print('\nBreakdown by occasion (category):')
        for o, c in occ_rows:
            print(f'  {o or "unset":10} → {c}')
        print('\n🎯 Each occasion now has dedicated, structured outfits for both genders.')


if __name__ == '__main__':
    run()
